### ISSUE TITLE
[Feat] 운전면허증 유효성 검증 API 

### ISSUE THREAD

**Issue by Chaeniiiii** [2024-1-Dongguk-CapstoneDesign/Lawing-SERVER#2]
## 🔥 Issue 내용
운전면허증 유효성 검증

## ✅ To-do
- [x] 운전면허증 정보 추출 (OCR)
- [x] 운전면허증 유효성 검증 기능
- [x] Codef 토큰 발급
