### ISSUE TITLE
[Feat] Custom Exception 구현

### ISSUE THREAD

**Issue by Chaeniiiii** [2024-1-Dongguk-CapstoneDesign/Lawing-SERVER#5]
## 🔥 Issue 내용
Custom Exception 구현

## ✅ To-do
- [x] Custom Exception 구현
- [x] Exception Handler 구현
- [x] ErrorResponse Entity 구현 
- [x] Error Code 구현
